---
title: "Preprocessing"
output: html_document
date: "2023-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
pacman::p_load(
  tidyverse,
  ggpubr,
  brms,
  cmdstanr,
  tidybayes,
  ggdist
)

library(ggdist)

theme_set(theme_bw())

options(mc.cores = parallel::detectCores(), 
        brms.backend = "cmdstanr", 
        control = list(adapt_delta = 0.9,
                       max_treedepth = 20)
        )
```


```{r}
# Load in data
df <- read_csv('Data/df.csv')
```


```{r}
df <- df %>%
  pivot_wider(names_from = trial_type,                   # Pivot the data to make trial_type values into columns
              values_from = c(onset, duration, trial_type),    # Select the values to populate the new columns
              names_glue = "{.value}_{trial_type}") %>%
  select(-ends_with("NA"))    # Remove columns ending with "NA"

df <- df %>%
  unite("onset_image", c("onset_image_neg", "onset_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("onset_word", c("onset_word_neg", "onset_word_neu", "onset_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("duration_image", c("duration_image_neg", "duration_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("duration_word", c("duration_word_neg", "duration_word_neu", "duration_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("trial_image", c("trial_type_image_neg", "trial_type_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("trial_word", c("trial_type_word_neg", "trial_type_word_neu", "trial_type_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE)  # Combine specific columns into new columns with specified names

df <- df %>%
  select(-starts_with("onset_image_neg"), -starts_with("onset_image_pos"),
         -starts_with("onset_word_neg"), -starts_with("onset_word_neu"), -starts_with("onset_word_pos"),
         -starts_with("duration_image_neg"), -starts_with("duration_image_pos"),
         -starts_with("duration_word_neg"), -starts_with("duration_word_neu"), -starts_with("duration_word_pos"),
         -starts_with("trial_image_neg"), -starts_with("trial_image_pos"),
         -starts_with("trial_word_neg"), -starts_with("trial_word_neu"), -starts_with("trial_word_pos"))  # Remove unnecessary columns

df <- df[, c("onset_image", "onset_word", "duration_image", "duration_word",
                       "trial_image", "trial_word", "response_time", "word",
                       "response", "correct_resp", "gender", "age", "sub", "ses",
                       "run", "year", "month", "day", "hour", "minute")]    # Reorder the columns

df <- df %>% 
  mutate(valence = !trial_word == 'word_neu') %>%    # Create a new column 'valence' based on the condition
  filter(!is.na(response_time) & response_time > 0) %>%    # Remove rows with missing or negative response_time values
  mutate(correct_resp = ifelse(sub == 101, 1-correct_resp,correct_resp))    # Update values in the 'correct_resp' column based on the condition
```


# Exploring data

```{r}
df
```


```{r}
df %>%
  ggplot() +
  aes(x=response_time,y=trial_image,fill=correct_resp,col=trial_word) +
  stat_halfeye(alpha=0.5) +
  xlim(0.3,1)
```


# Modeling

```{r}
form <- bf(response_time ~ 0 + trial_image + valence + (0+trial_image|sub),
           family = shifted_lognormal)

priors = c(
  prior(student_t(3,0,1),class='b'),
  prior(exponential(1),class='sigma'),
  prior(student_t(3,0,1),class='sd'),
  prior(lkj(1),class='cor'),
  prior(student_t(3,0,0.1),class='ndt',ub=min_Y)
)

get_prior(form,df)

mod <- brm(
  form,
  data = df,
  prior = priors,
  sample_prior = T
)
mod_prior <- brm(
  form,
  data = df,
  prior = priors,
  sample_prior = 'only'
)

pp_check(mod,ndraws=100)
pp_check(mod_prior,ndraws=100)+xlim(0,2.5)

?pp_check

summary(mod)

?student_t
```

```{r}
library(stringr)

# Sampling and updating the model
mod_samp <- as_draws_df(mod)

long <- mod_samp %>% 
  select(!c('lprior', 'lp__','.chain', '.iteration', '.draw',contains('r_sub['),contains('prior'))) %>% 
  pivot_longer(everything()) %>% 
  mutate(
    type = case_when(
      name %in% c('b_trial_imageimage_neg','b_trial_imageimage_pos','b_valenceTRUE') ~ "Population-level",
      name %in% c('sd_sub__trial_imageimage_neg','sd_sub__trial_imageimage_pos') ~ "Group-level",
      name %in% c('sigma','ndt','cor_sub__trial_imageimage_neg__trial_imageimage_pos') ~ "Technical"),
    name = case_when(
      name == 'b_valenceTRUE' ~  'Word informativeness',
      name == 'b_trial_imageimage_pos' ~  'Positive image, \u03B2',
      name == 'b_trial_imageimage_neg' ~  'Negative image, \u03B2',
      name == 'sd_sub__trial_imageimage_pos' ~  'Positive image, \u03C3',
      name == 'sd_sub__trial_imageimage_neg' ~  'Negative image, \u03C3',
      name == 'sigma' ~  '\u03C3',
      name == 'ndt' ~  'Shift, ndt',
      name == 'cor_sub__trial_imageimage_neg__trial_imageimage_pos' ~ 'Group-level correlation, ρ'
    )
)

long %>% ggplot()+
  aes(x=value,y=name)+
  stat_halfeye()+
  facet_wrap(~type,scales='free',nrow=3,strip.position="right")+xlab('Posterior values')+ylab('Model parameter')

#mod_update <- ggplot(mod_samp) +
#  geom_density(aes(prior_Intercept), fill="steelblue", color="black",alpha=0.6) +
#  geom_density(aes(b_Intercept), fill="#FC4E07", color="black",alpha=0.6) +
#  geom_density(aes(prior_sigma), fill="yellow", color="black",alpha=0.6) +
#  geom_density(aes(sigma), fill="green", color="black",alpha=0.6) +
#  labs(title = "posterior trial_image ~ 1 + response_time") + xlim(-2,2)

#mod_update

test <- mod_samp %>% 
  select(!c('lprior', 'lp__','.chain', '.iteration', '.draw',contains('r_sub['))) %>% 
  pivot_longer(everything()) %>% 
  mutate(draw_type = ifelse(grepl('prior',name),'prior','posterior'),
         class = ifelse(draw_type == 'posterior',sub("_.*","",name),str_extract(name,"_[a-zA-Z]*_?")) %>% gsub('_','',.))


prior_check <- left_join(test %>% filter(draw_type == 'posterior') %>% select(name,class) %>% distinct(),test %>% filter(draw_type == 'prior') %>% select(!name),by='class') %>% rbind(test) %>% 
  mutate(
    type = case_when(
      name %in% c('b_trial_imageimage_neg','b_trial_imageimage_pos','b_valenceTRUE') ~ "Population-level",
      name %in% c('sd_sub__trial_imageimage_neg','sd_sub__trial_imageimage_pos') ~ "Group-level",
      name %in% c('sigma','ndt','cor_sub__trial_imageimage_neg__trial_imageimage_pos') ~ "Technical"),
    name = case_when(
      name == 'b_valenceTRUE' ~  'Word informativeness',
      name == 'b_trial_imageimage_pos' ~  'Positive image, \u03B2',
      name == 'b_trial_imageimage_neg' ~  'Negative image, \u03B2',
      name == 'sd_sub__trial_imageimage_pos' ~  'Positive image, \u03C3',
      name == 'sd_sub__trial_imageimage_neg' ~  'Negative image, \u03C3',
      name == 'sigma' ~  '\u03C3',
      name == 'ndt' ~  'Shift, ndt',
      name == 'cor_sub__trial_imageimage_neg__trial_imageimage_pos' ~ 'Group-level correlation, ρ'
    )
)


names <- test %>% filter(draw_type == 'posterior') %>% select(name,class) %>% distinct()
prior_draws_df <- test %>% filter(draw_type == 'prior') %>% select(!name)
posterior_draws_df <- test %>% filter(draw_type == 'posterior')


left_join(names,prior_draws_df,by='class') %>% rbind(posterior_draws_df) %>% 
  mutate(
    type = case_when(
      name %in% c('b_trial_imageimage_neg','b_trial_imageimage_pos','b_valenceTRUE') ~ "Population-level",
      name %in% c('sd_sub__trial_imageimage_neg','sd_sub__trial_imageimage_pos') ~ "Group-level",
      name %in% c('sigma','ndt','cor_sub__trial_imageimage_neg__trial_imageimage_pos') ~ "Technical"),
    name = case_when(
      name == 'b_valenceTRUE' ~  'Word informativeness',
      name == 'b_trial_imageimage_pos' ~  'Positive image, \u03B2',
      name == 'b_trial_imageimage_neg' ~  'Negative image, \u03B2',
      name == 'sd_sub__trial_imageimage_pos' ~  'Positive image, \u03C3',
      name == 'sd_sub__trial_imageimage_neg' ~  'Negative image, \u03C3',
      name == 'sigma' ~  '\u03C3',
      name == 'ndt' ~  'Shift, ndt',
      name == 'cor_sub__trial_imageimage_neg__trial_imageimage_pos' ~ 'Group-level correlation, ρ'
    )
) %>% 
ggplot()+
  aes(x=value,y=name,color=draw_type)+
  stat_halfeye()+
  facet_wrap(~type,scales='free',nrow=3,strip.position="right")+xlab('Values')+ylab('Model parameter')+labs(color = "Type")

```


## Hypothesis testing
```{r}
hypothesis(mod, "trial_imageimage_neg>trial_imageimage_pos")

# put some more test we can put
get_prior(form,df)
```



