---
title: "Preprocessing"
output: html_document
date: "2023-04-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
pacman::p_load(
  tidyverse,
  ggpubr,
  brms,
  cmdstanr,
  tidybayes,
  ggdist
)

library(ggdist)

theme_set(theme_bw())

options(mc.cores = parallel::detectCores(), 
        brms.backend = "cmdstanr", 
        control = list(adapt_delta = 0.9,
                       max_treedepth = 20)
        )

df <- read_csv('Data/df.csv')
```



```{r}
df <- df %>%
  pivot_wider(names_from = trial_type,                   # Pivot the data to make trial_type values into columns
              values_from = c(onset, duration, trial_type),    # Select the values to populate the new columns
              names_glue = "{.value}_{trial_type}") %>%
  select(-ends_with("NA"))    # Remove columns ending with "NA"

df <- df %>%
  unite("onset_image", c("onset_image_neg", "onset_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("onset_word", c("onset_word_neg", "onset_word_neu", "onset_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("duration_image", c("duration_image_neg", "duration_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("duration_word", c("duration_word_neg", "duration_word_neu", "duration_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("trial_image", c("trial_type_image_neg", "trial_type_image_pos"), sep = "_", remove = FALSE, na.rm = TRUE) %>%
  unite("trial_word", c("trial_type_word_neg", "trial_type_word_neu", "trial_type_word_pos"), sep = "_", remove = FALSE, na.rm = TRUE)  # Combine specific columns into new columns with specified names

df <- df %>%
  select(-starts_with("onset_image_neg"), -starts_with("onset_image_pos"),
         -starts_with("onset_word_neg"), -starts_with("onset_word_neu"), -starts_with("onset_word_pos"),
         -starts_with("duration_image_neg"), -starts_with("duration_image_pos"),
         -starts_with("duration_word_neg"), -starts_with("duration_word_neu"), -starts_with("duration_word_pos"),
         -starts_with("trial_image_neg"), -starts_with("trial_image_pos"),
         -starts_with("trial_word_neg"), -starts_with("trial_word_neu"), -starts_with("trial_word_pos"))  # Remove unnecessary columns

df <- df[, c("onset_image", "onset_word", "duration_image", "duration_word",
                       "trial_image", "trial_word", "response_time", "word",
                       "response", "correct_resp", "gender", "age", "sub", "ses",
                       "run", "year", "month", "day", "hour", "minute")]    # Reorder the columns

df <- df %>% 
  mutate(valence = !trial_word == 'word_neu') %>%    # Create a new column 'valence' based on the condition
  filter(!is.na(response_time) & response_time > 0) %>%    # Remove rows with missing or negative response_time values
  mutate(correct_resp = ifelse(sub == 101, 1-correct_resp,correct_resp))    # Update values in the 'correct_resp' column based on the condition
```

```{r}
df
```


```{r}
# Use ifelse statements to assign values based on conditions
df$accuracy <- ifelse(df$trial_image == "image_neg" & df$response == "b", 0,
                      ifelse(df$trial_image == "image_neg" & df$response == "y", 1,
                             ifelse(df$trial_image == "image_pos" & df$response == "b", 1,
                                    ifelse(df$trial_image == "image_pos" & df$response == "y", 0, NA))))
```



# Exploring data

```{r}
df %>%
  ggplot() +
  aes(x=response_time,y=trial_image,fill=correct_resp,col=trial_word) +
  stat_halfeye(alpha=0.5) +
  xlim(0.3,1)
```


# Modeling

```{r}
form <- bf(trial_image ~ 1+response_time,
           family = gaussian)

priors = get_prior(form,df)


mod1 <- brm(
  form,
  data = df,
  prior = priors
)


pp_check(mod1,ndraws=100)

summary(mod3)

df
```

```{r}
get_prior(form,df)
```







```{r}
df %>% ggplot()+aes(x=acc,y=gender,color=run %>% as.factor())+geom_point()
```

